### ISSUE TITLE
Load file : closing quotation is missing for the uuid alt-0-0-1-op-s-3021 in logical-termination-point list

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#1]
In the load file ApplicationLayerTopology_0.0.2_tsi.220110.1955+data.1 , for the uuid alt-0-0-1-op-s-3021 in logical-termination-point list , closing quotation mark is missing. (This creates a parsing error while trying to read the json file from application )

**Comment by openBackhaul** [comment]
In line 811, the closing quotation mark has to be added.

**Comment by openBackhaul** [comment]
Seems to be fixed before.
No uuid ending on _021_ could be found without closing quotation mark.
JSON validator results in ok.
