### ISSUE TITLE
Basic services

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationLayerTopology#101]
Some OperationClients have to be changed from "basic management" to "basic services":
- ExecutionAndTraceLog://v1/record-service-request
- OamLog://v1/record-oam-request
- AdministratorAdministration://v1/approve-oam-request

**Required changes in ServiceList:**
- move three OperationClients from own-oam::basic to service::basic
- change uuids from e.g. tar-1-0-0-op-c-0040 to tar-1-0-0-op-c-bs-eatl-1-0-0-000 (make off-line table of changes!)

**Required changes in ForwardingList:**
- update uuids (by CTRL+h)

**Required changes in CONFIGfile:**
- move OperationClients
- update uuids of OperationClient (by CTRL+h) according to table
- update uuids of HttpClient and TcpClient

**Required changes in OAS:**
- update uuids of OperationClients, HttpClients and TcpClients (by CTRL+h) according to table

**Comment by kmohr-soprasteria** [comment]
PR #105 already covers the renamings of all uuids in the various files.  
The ordering of uuids differs between serviceList and config file:  
![vergleich](https://user-images.githubusercontent.com/57349523/203552542-e200ce15-cc14-41e1-bdc0-4f4c68ff83c2.jpg)

**Comment by openBackhaul** [comment]
Done
