### ISSUE TITLE
Update UUIDs of Services

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationLayerTopology#104]

**Comment by kmohr-soprasteria** [comment]
mapping table:
[mappings.txt](https://github.com/openBackhaul/ApplicationLayerTopology/files/10032524/mappings.txt)

**Comment by kmohr-soprasteria** [comment]
**config file**  
- Mapped the uuids for all applications except RegistryOffice in the config file. Don't have a mapping for ro-1-0-0 uuids (RO repo already has 2.0.0 uuids)
- deleted entries for old invalid uuids from other TAC applications, see attached findings list.

[findings_configfile.txt](https://github.com/openBackhaul/ApplicationLayerTopology/files/10034294/findings_configfile.txt)
[missing mappings for ro-uuids.txt](https://github.com/openBackhaul/ApplicationLayerTopology/files/10034306/missing.mappings.for.ro-uuids.txt)

**Comment by kmohr-soprasteria** [comment]
After feedback from Iswaryaa updated config file again and only changed uuids for ALT, but not other TAC apps:
```
•	In ALT data file, other than “alt” control-construct, other control-construct(s) (like RO, TAR, AA, EaTL, OL) they need not be updated for uuid(s) currently since they become a part of Application data and not config data. 
•	Updating them here would become a redundant task since these data are already updated in respective application’s repository. So, once we complete all updates in data file, control-construct form other applications can be copied without attributes like operation-key and detailed-logging-is-on. 
•	On the other hand, in v2.0.0, current ALT data file would be segregated to config and data files with config file containing profile, ALT control-construct whereas data file will have control-construct data of ALT’s client applications. 
```
