### ISSUE TITLE
Updating the UUIDs of FCs

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#108]
Process for updating the UUIDs of FCs

- [x] Katharina to update fc-uuid in CONFIGfile and OAS wherever applicable referencing from ForwardingList on feature branch
- [x] Katharina to create pull request from feature branch
- [ ] Iswaryaa to review the pull request
If no errors found
- [ ] Iswaryaa to Approve the pull request
- [ ] Iswaryaa to merge feature branch to develop
- [ ] Iswaryaa to delete feature branch and close this issue

**Comment by kmohr-soprasteria** [comment]
![mapping](https://user-images.githubusercontent.com/57349523/203324266-aae89cc3-3e34-4e5e-8387-22c7e781c183.png)
