### ISSUE TITLE
Use new ConfigurationInput and LogicalTerminationPointServices

### ISSUE THREAD

**Issue by MartinSunal** [openBackhaul/ApplicationLayerTopology#122]
Create a mapping file for individual services used in this application and use new classes from ApplicationPattern with it.

Application Pattern [#284](https://github.com/openBackhaul/ApplicationPattern/issues/284) [#346](https://github.com/openBackhaul/ApplicationPattern/issues/346)

**Comment by DanaSunal** [comment]
Fixed by #249
