### ISSUE TITLE
Individual service /v1/list-application additional logic needs to be removed

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#147]
Current logic to lists the application is based on the control-construct instance availability for regarded application. 
If a application is regarded and there is no control-construct instance is available for this regarded application , 
then,
the "list-application" service will not consider that regarded application for the response.

This additional logic is not required as the specification recommends to refer the http-client instance , 
/core-model-1-4:control-construct/logical-termination-point=alt-2-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name.

Please remove this logic and make sure all the applications that are regarded shall be listed in the response based on the configuration data.

**Comment by vanithavalluripalli9** [comment]
This issue is closed with changes in pull request https://github.com/openBackhaul/ApplicationLayerTopology/pull/250
