### ISSUE TITLE
Impact in ALT when an existing application gets upgraded to new version 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#158]
> Note : Based on further discussion , milestone for this issue shall be decided.

ALT stores operation-clients and operation-servers of all the applications to, 
•	establish connection between an operation-server to multiple operation-clients across applications.
•	provide correct uuids of operation-clients and operation-servers to OKM to set the operations keys for secured communication. 

**Assumption :**
Not changing the operation-client uuids based when there is a change in the application-name and release-number.

**Context :**
(Taking EALT application and its “record-service-request” service for illustration purpose)
In ALT , the link between EATL “record-service-request” and its client looks as below , 
  
![image](https://user-images.githubusercontent.com/62344562/207112557-5ce55546-8bc0-47f3-b799-d034d0f794fd.png)

When EATL upgrades from version 4.0.0 to version 5.0.0 , 
1.	RO will send regard-application to all subscription for “notify-approvals” including ALT and ALT creates a control-construct instance based on the responseBody of “redirect-topology-change-information”.
2.	RO sends update-client to all application which updates the http-client-configuration/release-number but not the uuids. 
3.	RO sends disregard-application to all applications which removes the details of EATL version 4.0.0. Also, ALT removes the control-construct instance of eatl-4-0-0 from the list of CCs. But still , links will hold the same information as the above picture.

**Consequence :**
When OKM seeks for the end point details from ALT using the service /v1/list-end-points-of-link with the information of the link-uuid alt-4-0-0-op-link-3004 , 
•	ALT cannot be able to provide information for the OUTPUT “eatl-4-0-0-op-s-is-004” as the corresponding control-construct doesn’t exists. Even if the control-construct information exists , we are not pointing to a correct instance.
•	All the operation-clients will be updated with the latest operationKey. 
•	But the new operation-server will not receive the latest operationKey.

**Workaround :**
Create new links for between the new application version to all the operation-clients.

**Next step :**
Finding a logic in the server-side code to not lose the already approved links.

**Comment by openBackhaul** [comment]
Based on above example:
....
When EATL upgrades from version 4.0.0 to version 5.0.0 , 
1. RO will send regard-application to all subscription for “notify-approvals” including ALT and ...
  a) ... ALT creates a control-construct for communicating with EATL version 5.0.0 in its CONFIG
  b) ... ALT sends _EaTL5.0.0://redirect-topology-change-information_
  c) ... ALT creates a control-construct for EATL version 5.0.0 based on the responseBody of “redirect-topology-change-information” in its application data
  d) ... ALT creates a Link for every OperationServer at the newly created application in its application data
3. RO sends update-client to all applications, which results in ...
  a) ... all "conventional" application to update the http-client-configuration/release-number, but not the uuids
  b) ... ALT also to update the http-client-configuration/release-number (but not the UUIDs) in its CONFIG data, but not in its application data
4. Every update of an HttpClient or TcpClient either according to 2a) or 2b) results in...
  a) ... the respective application calling ALT://v1/update-ltp
  b) (... no calls to ALT://v1/update-fc or ALT://v1/update-fc-port, because, UUIDs of HttpClient and TcpClient are invariant and modifications of the FC or FcPort are not required)
5. Whenever calling ALT://v1/update-ltp is communicating new application name or release number of an HttpClient, ALT has to 
  a) ... update the corresponding values in the HttpClient in its application data
  b) ... has to search through existing Links for UUIDs of the OperationClients, which are ClientLtp to the updated HttpClient
  c) ... found OperationClient-UUIDs have to be ...
    - ... deleted from the existing Links 
    - ... added to the newly created Links (see step 1d). Correct Link to be identified by searching Links for correct OperationServer-UUID. OperationServer-UUID to be found by searching for application name and release number in ServingLtp of OperationServer with same operation name as found in OperationClient with OperationClient-UUIDs .
6. RO sends disregard-application to all applications
  a) ... all applications search for HttpClients with application name and release number and remove all associated objects like TcpClients, OperationClients, FC, FcPorts etc. . Presumably, they won't find anything to delete, since existing HttpClient has been updated by new application name and release number before.
  b) ... same for ALT search its CONFIG
  c) ... ALT searching application data for HttpServer with application name and release number and removes all associated objects like TcpServers, OperationServers, FCs, FcPorts etc.  and Links.

**Comment by PrathibaJee** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



1 | RO will send regard-application   to all subscription for “notify-approvals” including ALT and … |  
-- | -- | --
  | a)   ... ALT creates HttpClients, TcpClients and OperationClients for   communicating with EATL version 5.0.0 in its CONFIG | Yes
  | b)   ... ALT sends EaTL5.0.0://redirect-topology-change-information | Yes
  | c)   ... ALT creates a control-construct for EATL version 5.0.0 based on the   responseBody of EaTL5.0.0://redirect-topology-change-information in   its application data | Yes
  | d)   ... ALT creates a Link for every OperationServer at the newly created EATL   version 5.0.0 in its application data | Current implementation of ALT   server side code is not like so. Links will be created on demand based on the   service /v1/add-operation-client-to-link.     If a link is not available for an operation-server , then a link instance   will be created with OUTPUT link-port for the operation-server. We can   include the logic mentioned in 1.d in the implementation.     Example :      link {     OUTPUT : "op-s of EATL version 4.0.0 =   "v1/record-service-request"",     INPUT : "op-c of EATL version 4.0.0 in RO =   "v1/record-service-request"",     INPUT : "op-c of EATL version 4.0.0 in TAR =   "v1/record-service-request""     ...     }          link {     OUTPUT : "op-s of EATL version 5.0.0 =   "v1/record-service-request""     }
  |   |  
  | Before point#2 , i.e the   /v1/update-client , there is one more flow is there in case of EATL. New   version of EATL 5.0.0 will send   "/v1/redirect-service-request-information" to all application. But   this will fail because still there is no approval available already | But by using update client this information shall be updated.
  |   |  
2 | RO sends /v1/update-client to   all applications, which results in … |  
  | a) ... all applications, which   do not yet comprise an EATL version 5.0.0 HttpClient to update the HttpClient   from EATL version 4.0.0 to 5.0.0, but not its UUID | yes
  | b) ... ALT not to update the   HttpClient from EATL version 4.0.0 to 5.0.0, because it already created an   EATL version 5.0.0 HttpClient after receiving /v1/regard-application | yes
  | c) ... ALT also not to update   any content in its application data | yes
  |   |  
3 | Every update of an existing   HttpClient or TcpClient caused by 2a) in any other application results in... |  
  | a) ... the respective   application calling ALT://v1/update-ltp | yes
  | b) ... no calls to   ALT://v1/update-fc or ALT://v1/update-fc-port, because, UUIDs of HttpClient   and TcpClient are invariant and FCs and FcPorts don't get modified | yes
  |   |  
4 | Whenever ALT   receiving ALT://v1/update-ltp with new application name or release   number of an HttpClient, ALT has to |  
  | a) ... update the corresponding   values in the HttpClient in its application data | yes
  | b) ... has to search through   existing Links for UUIDs of the OperationClients, which are ClientLtp to the   updated HttpClient |  
  | c) ... found   OperationClient-UUIDs have to be ... |  
  | o	... deleted from the existing   Links |  
  | o	... added to the newly created   Links (see step 1d). |  
  | Correct Link to be identified by   searching Links for correct OperationServer-UUID. | yes



</body>

</html>

**Comment by PrathibaJee** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



1 | RO will send regard-application   to all subscription for “notify-approvals” including ALT and … |  
-- | -- | --
  | a)   ... ALT creates HttpClients, TcpClients and OperationClients for   communicating with EATL version 5.0.0 in its CONFIG | Yes
  | b)   ... ALT sends EaTL5.0.0://redirect-topology-change-information | Yes
  | c)   ... ALT creates a control-construct for EATL version 5.0.0 based on the   responseBody of EaTL5.0.0://redirect-topology-change-information in   its application data | Yes
  | d)   ... ALT creates a Link for every OperationServer at the newly created EATL   version 5.0.0 in its application data | Current implementation of ALT   server side code is not like so. Links will be created on demand based on the   service /v1/add-operation-client-to-link.     If a link is not available for an operation-server , then a link instance   will be created with OUTPUT link-port for the operation-server. We can   include the logic mentioned in 1.d in the implementation.     Example :      link {     OUTPUT : "op-s of EATL version 4.0.0 =   "v1/record-service-request"",     INPUT : "op-c of EATL version 4.0.0 in RO =   "v1/record-service-request"",     INPUT : "op-c of EATL version 4.0.0 in TAR =   "v1/record-service-request""     ...     }          link {     OUTPUT : "op-s of EATL version 5.0.0 =   "v1/record-service-request""     }
  |   |  
  | Before point#2 , i.e the   /v1/update-client , there is one more flow is there in case of EATL. New   version of EATL 5.0.0 will send   "/v1/redirect-service-request-information" to all application. But   this will fail because still there is no approval available already | But by using update client this information shall be updated.
  |   |  
2 | RO sends /v1/update-client to   all applications, which results in … |  
  | a) ... all applications, which   do not yet comprise an EATL version 5.0.0 HttpClient to update the HttpClient   from EATL version 4.0.0 to 5.0.0, but not its UUID | yes
  | b) ... ALT not to update the   HttpClient from EATL version 4.0.0 to 5.0.0, because it already created an   EATL version 5.0.0 HttpClient after receiving /v1/regard-application | yes
  | c) ... ALT also not to update   any content in its application data | yes
  |   |  
3 | Every update of an existing   HttpClient or TcpClient caused by 2a) in any other application results in... |  
  | a) ... the respective   application calling ALT://v1/update-ltp | yes
  | b) ... no calls to   ALT://v1/update-fc or ALT://v1/update-fc-port, because, UUIDs of HttpClient   and TcpClient are invariant and FCs and FcPorts don't get modified | yes
  |   |  
4 | Whenever ALT   receiving ALT://v1/update-ltp with new application name or release   number of an HttpClient, ALT has to |  
  | a) ... update the corresponding   values in the HttpClient in its application data | yes
  | b) ... has to search through   existing Links for UUIDs of the OperationClients, which are ClientLtp to the   updated HttpClient |  
  | c) ... found   OperationClient-UUIDs have to be ... |  
  | o	... deleted from the existing   Links |  
  | o	... added to the newly created   Links (see step 1d). |  
  | Correct Link to be identified by   searching Links for correct OperationServer-UUID. | yes



</body>

</html>

**Comment by PrathibaJee** [comment]
Aim : To transfer the operationClientUUIDs of a link from a previous release to a new release of an application (or) from a deprecated service name to a new service name.


In the provided [comment](https://github.com/openBackhaul/ApplicationLayerTopology/issues/158#issuecomment-1356355522), the main logic is in the point#4 and #5. And 1.d and 6.b makes sure to have enough data to support the logic in point#4 and #5.

**Following scenarios are considered to validate this logic :**
1. Existing application release number gets upgraded
      - Consuming applications receive the client upgrade via regard-application and update-client
      - Consuming applications that receives the client upgrade via only update-client
2. Existing application release number and operation-servers gets upgraded
      - Consuming applications that receives the operation-client upgrade via update-operation-client 
      - Consuming applications that receives the operation-client upgrade via update-operation-client and subscription notification
3. Application that went down in port and container brought up in another port (no change required in links)

**Not validated the following scenario in detail: ** 
      1. Application name is upgraded (when checked in high level, this will work. Didn’t check end to end as this is a rare scenario)

**The mentioned logic will work and it requires some changes in the implementation as well as the spec(OAS,config).** 

----------------------------------
> 1.d) ... ALT creates a Link for every OperationServer at the newly created EATL version 5.0.0 in its application data

Current implementation of ALT server side code is not like so. Links will be created on demand based on the service /v1/add-operation-client-to-link.
(If a link is not available for an operation-server , then a link instance will be created with OUTPUT link-port for the operation-server.)
Created the following issues to include this changes , 
specification issue: [ApplicationLayerTopology/issues/192](https://github.com/openBackhaul/ApplicationLayerTopology/issues/192)
Implementation issue : [ApplicationLayerTopology/issues/193](https://github.com/openBackhaul/ApplicationLayerTopology/issues/193)

----------------------------------

> 6.b) Disregard-application should not delete the application data

specification issue: [ApplicationLayerTopology/issues/196](https://github.com/openBackhaul/ApplicationLayerTopology/issues/196)
Implementation issue : [ApplicationLayerTopology/issues/197](https://github.com/openBackhaul/ApplicationLayerTopology/issues/197)

----------------------------------

To enhance the /v1/update-ltp logic mentioned in the point#4 and #5 , Instead of creating and deleting the links internally , we shall utilize the services /v1/add-operation-clients-to-link and /v1/remove-operation-clients-from-links to facilitate updating links and initiate corresponding forwardings. Mentioned this in the following Proposal#2.

specification issue: [ApplicationLayerTopology/issues/194](https://github.com/openBackhaul/ApplicationLayerTopology/issues/194)
Implementation issue : [ApplicationLayerTopology/issues/195](https://github.com/openBackhaul/ApplicationLayerTopology/issues/195)


Many thanks to @IswaryaaS for multiple discussion over teams call.

**Comment by PrathibaJee** [comment]
Moving the issue from the milestone **v2.0.0_spec** to **v2.0.0_impl** as the following child issues created to complement the specifications are closed , 
[ApplicationLayerTopology/issues/192](https://github.com/openBackhaul/ApplicationLayerTopology/issues/192)
[ApplicationLayerTopology/issues/196](https://github.com/openBackhaul/ApplicationLayerTopology/issues/196)
[ApplicationLayerTopology/issues/194](https://github.com/openBackhaul/ApplicationLayerTopology/issues/194)

**Comment by vanithavalluripalli9** [comment]
Closing the issue as the child issues related to implementation mentioned below are closed : 
https://github.com/openBackhaul/ApplicationLayerTopology/issues/193
https://github.com/openBackhaul/ApplicationLayerTopology/issues/197
https://github.com/openBackhaul/ApplicationLayerTopology/issues/195
