### ISSUE TITLE
New link instance with OUTPUT link-ports to be created for newly regarded application's operation servers

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#192]
Currently , when a new application is regarded , “redirect-topology-request-information” will be sent to the regarded application.
The response of “redirect-topology-request-information” , consists of the LTP and FC of the application.
And as per the discussion in the [comment 1.d)](https://github.com/openBackhaul/ApplicationLayerTopology/issues/158#issuecomment-1356355522) , 
ALT shall further creates ...
- control-construct instance for the received data in the ApplicationData (i.e) elastic search
- new link instances for all the operationServers of the newly regarded application. 

Proposal : 
In the OAS of ALT , 
In the callback NewApplicationCausesRequestForTopologyChangeInformation , a description shall be added that states this information “New links will be created for all the exposed services”.

**Comment by openBackhaul** [comment]
After correcting the ResponseBody of callback /v1/regard-application::NewApplicationCausesRequestForTopologyChangeInformation the description _'Client side for sending information about topology changes has been updated and current data tree has been provided'_ shall be changed towards _'Client side for sending information about topology changes has been updated and current data tree has been provided. Links shall be complemented for the OperationServers.'_
