### ISSUE TITLE
To include new forwardings for the service /v1/update-ltp

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#194]
As per the discussion in the [comment ](https://github.com/openBackhaul/ApplicationLayerTopology/issues/158#issuecomment-1356355522) . as a part of /v1/update-ltp  , if there is a need to transfer the links from one link instance to another , we should 
- delete operationClientUUIDs from invalid links
- add operationClientUUIDs to the valid links
- forward the regarded link information to OKM::/v1/regard-updated-link

Adding/removing of links shall be either 
- handled directly inside the implementation logic of ALT and forwarding shall be initiated to OKM::/v1/regard-updated-link
or 
- ALT::/v1/add-operation-clients-to-link and ALT::/v1/remove-operation-clients-from-links services shall be used to create/delete links.

Kindly please find below proposals for both the concepts , 
**Proposal#1 : Updating links directly in the implementation logic.**
      **OAS :** A note shall be included in the description that indicates that changes to Http/operation client leads to update in the links 
      **CONFIG file :** a INPUT fc-port for the /v1/update-ltp(alt-2-0-0-op-s-is-005)  shall be added to the LinkChangeNotification(alt-2-0-0-op-fc-is-002) forwardingConstruct 

**Proposal#2 : initiate /v1/add-operation-clients-to-link and /v1/remove-operation-clients-from-links services to add/remove links**
**OAS :** A note shall be included in the description that indicates that changes to Http/operation client leads to update in the links 
**CONFIG file :** 
Two new invariant forwardingConstruct instance shall be included in the CONFIG file , 
1. forwardingConstruct-1 between /v1/update-ltp(alt-2-0-0-op-s-is-005) and /v1/add-operation-clients-to-link(alt-2-0-0-op-s-is-018)
2. forwardingConstruct-2 between /v1/update-ltp(alt-2-0-0-op-s-is-005)  and /v1/remove-operation-clients-from-link(alt-2-0-0-op-s-is-019)
> OKM::/v1/regard-updated-link will be initiated as a part of /v1/add-operation-clients-to-link and /v1/remove-operation-clients-from-link service forwardings

Elaborated the server-side logic in a separate [issue](https://github.com/openBackhaul/ApplicationLayerTopology/issues/195).

**Comment by openBackhaul** [comment]
**Following changes to be made:**
- [ ] Update ServiceList with new OperationClients at ALT
- [ ] Update ForwardingList with 3 new Forwardings
- [ ] Update CONFIGfile by 
  - [ ] new OperationClients at ALT
  - [ ] new 3 Forwardings
- [ ] Update OAS by 
  - [ ] 2 additional callbacks at /v1/update-ltp
  - [ ] 1 additional callback at /v1/delete-ltp-and-dependents
