### ISSUE TITLE
/v1/disregard-application summary needs to include information to not delete applicationData while deleting an application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#196]
As per the discussion in the [comment ](https://github.com/openBackhaul/ApplicationLayerTopology/issues/158#issuecomment-1356355522) , applicationData shall not be deleted while disregarding an application from the ApplicationLayerTopology application.

This information shall be documented in the /v1/disregard-application service summary and response/204/description.

**Comment by openBackhaul** [comment]
Description of /v1/disregard-application shall be changed from _'Removes application from application layer topology representation'_ towards _'Removes application from ApplicationLayerTopology's configuration'_
