### ISSUE TITLE
/v1/disregard-application to not delete applicationData while deleting an application from ALT

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#197]
As per the [ApplicationLayerTopology/issues/196](https://github.com/openBackhaul/ApplicationLayerTopology/issues/196) , /v1/disregard-application should delete only the configuration information , but not the applicationData of the disregarded application.

**Comment by vanithavalluripalli9** [comment]
The issue is closed with the chages in pull request https://github.com/openBackhaul/ApplicationLayerTopology/pull/248
