### ISSUE TITLE
Include uuid syntax for the /v1/redirect-topology-change-information attribute for the service regard-application 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#204]
As a part of regard-application , for the basic service “/v1/redirect-topology-change-information” a new operation-client will be created for the regarded application.
As per the specification , the reserved uuid syntax for this operationName is 
```
<own application abbreviation>-<release-number-of-own-separated-by-hypens>-op-c-im-<application abbreviation>-<release-number-separated-by-hypens>-004
```
Create a OperationClient if not available. Update the OperationClient configuration if the client is already available.

Also , currently this is “redirect-service-request-information” hardcoded in the serverside logic.

**Comment by vanithavalluripalli9** [comment]
This issue is fixed with changes in puul request https://github.com/openBackhaul/ApplicationLayerTopology/pull/249

**Comment by DanaSunal** [comment]
The pull request does not change the UUID, there is still old UUID in develop branch.
