### ISSUE TITLE
Include uuid syntax for the subscriber-operation attribute for the service /v1/notify-link-updates

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#225]
As per the specification , the reserved uuid syntax for the operationName in the subscriber-operation is 
```
<own application abbreviation>-<release-number-of-own-separated-by-hypens>-op-c-is-<application abbreviation>-<release-number-separated-by-hypens>-000 ` for ‘regard-application’
```

Create a OperationClient if not available. Update the OperationClient configuration if the client is already available.

**Comment by IswaryaaS** [comment]
As per decision made on issue https://github.com/openBackhaul/ApplicationLayerTopology/issues/231, pattern uuid for /v1/notify-link-updates needs an update. 

```
<own application abbreviation>-<release-number-of-own-separated-by-hypens>-op-c-is-<application abbreviation>-<release-number-separated-by-hypens>-002 ` for ‘regard-application’
```

**Comment by vanithavalluripalli9** [comment]
This issue is closed with changes in pull request https://github.com/openBackhaul/ApplicationLayerTopology/pull/251

**Comment by DanaSunal** [comment]
The mentioned pull request does not fix the issue. Nor does any other. I can still see the old UUID in the [mapping file](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/server/service/individualServices/IndividualServicesOperationsMapping.js) on develop branch.
