### ISSUE TITLE
LocalProtocol and RemoteProtocol values in CONFIGfile to follow ONF notation

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#233]
As per issue https://github.com/openBackhaul/ApplicationPattern/issues/519, local-protocol and remote-protocol attributes in config file shall be updated according to ONF format

enum:
- 'tcp-server-interface-1-0:PROTOCOL_TYPE_HTTP'
- 'tcp-server-interface-1-0:PROTOCOL_TYPE_HTTPS'
- 'tcp-server-interface-1-0:PROTOCOL_TYPE_NOT_YET_DEFINED'

enum:
- 'tcp-client-interface-1-0:PROTOCOL_TYPE_HTTP'
- 'tcp-client-interface-1-0:PROTOCOL_TYPE_HTTPS'
- 'tcp-client-interface-1-0:PROTOCOL_TYPE_NOT_YET_DEFINED'

**Comment by openBackhaul** [comment]
Pull-request #232 merged.
