### ISSUE TITLE
'Link' representation in Elasticsearch

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationLayerTopology#246]
It needs to be decided how Links will be represented in Elasticsearch.
Current implementation is that they are present in load file, but outside control-construct.
For control-construct purposes, ALT already creates an index with mapping fields 'uuid', 'logical-termination-point', 'profile-collection', 'forwarding-domain' for it's new index. The question remains, how to represent Links.

1. Option:

Create new index under existing index alias and leave all logic within ALT and Elasticsearch. This approach means, that the operator has no control over such index. This new index will inherit the same service policy as the one set on index-alias.

Example: 
index-alias: alt-2-0-1
ALT will create index 'alt-2-0-1-00001' where it will store control constructs for all regarded applications.
ALT will also create index 'alt-2-0-1-links-00001' where it will store links.

2. Option:

Create new index alias for Links. This approach means, the operator can specify a different service policy for this index-alias.

Example: 
index-alias: alt-2-0-1
ALT will create index 'alt-2-0-1-00001' where it will store control constructs for all regarded applications.
links-index-alias: alt-links-2-0-1
ALT will also create index 'alt-links-2-0-1-00001' where it will store links. This index does not inherit the service policy from index-alias.

Option 2 has more control, but adds additional complexity (we need to specify in requests the correct UUID).

Main question is, if there is a need to use a service policy for ALT, and if so, if it needs to differ between storages of control-constructs and Links.

**Comment by DanaSunal** [comment]
After doing additional research, given the amount of data expected, the easiest option to implement and maintain would be just adding another field 'links' to existing index. This field would be empty in all control-construct except alt.

**Comment by openBackhaul** [comment]
Call on 17th of February:
Potentially, a second ElasticSearch client shall be documented in the CONFIGfile. (Impact on other parts of the specification, too?)
Dana will be analyzing the ES behavior and provides feedback about necessary changes to the specification.

**Comment by DanaSunal** [comment]
Second index-alias seems to be working fine. Some small adjustment had to be made in the code of Elasticsearchservice in ApplicationPattern and also to ALT specification: I've added the second ES client to load file here:
https://github.com/openBackhaul/ApplicationLayerTopology/pull/242/files#diff-a313e699e459e7f767762bc5b814dd09c1a404c6aea3a66773ab5155d95f921d

**Comment by DanaSunal** [comment]
Also, as Vanitha pointed out, in specification, the descriptions in ALT specification needs to be updated to omit network-control-domain. The concept of network-control-domain is no longer needed, as all control constructs will be stored under one index (each control construct will be a document) and all links will be stored under other index (each link will be a document).

**Comment by DanaSunal** [comment]
Please remove from specification description:
Instead of:
`              description: >
    'Documentation of an interface at an application
    update or create [ElasticSearch://core-model-1-4:network-control-domain/control-construct=*/logical-termination-point=*/]'` 

Put: `              description: >
    'Documentation of an interface at an application
    update or create [ElasticSearch://logical-termination-point=*/]'`
