### ISSUE TITLE
Method not allowed - correct procedure

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationLayerTopology#253]
ALT defined in its specification REST API methods for getting and setting service records policy. However, service records policy won't be used in this application. This question is about proper behavior of the application (or setting a precedence what to do, in case something like this happens in other applications.) when it encounters a REST  API method that will not be implemented.

Following options need to be analyzed and one picked:

1. **delete get/setServiceRecordsPolicy from API specification** ( I was told, that this is not an option, in order to keep API same for all applications.).  -- no further action on server side is needed
2. **delete only controller methods on server side** -- default message and status code will be returned 
3. **allow those methods to return also [405 Method Not Allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405)** -- this must be implemented in specification, the return code should be added to ApplicationPattern and code in ALT needs to return this status code
4. **implement the methods on server side, return existing status code 400** (this does not really tell the real reason why an error is returned and can be confused with not-expected application behavior)
5. **implement the methods on server side, return existing status code 200** (this does not really tell the real reason why was the request successful with no data to be returned and can be confused with expected application behavior)

In options 3,4,5 the question is also, if this request should be logged by OAMLog application.

**Comment by DanaSunal** [comment]
Conclusion: correct procedure to implement is:
`3. allow those methods to return also [405 Method Not Allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405) -- this must be implemented in specification, the return code should be added to ApplicationPattern and code in ALT needs to return this status code`

Created #263 to track specification changes.
Created #264 to track implementation changes in ALT.
Created openBackhaul/ApplicationPattern#593 to track changes in Application Pattern.

**Comment by IswaryaaS** [comment]
As per last discussion, we need to recheck if 405 Method not allowed would be a correct response code for this scenario. The proposed response code is 404. 
Assigning back to Dana for rechecking

**Comment by openBackhaul** [comment]
Path deleted from specification.
