### ISSUE TITLE
Change Link UUID examples to uuidv4 format and remove the UUID regex pattern

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationLayerTopology#286]
The specification has examples in old format, but new UUIDs are generated using uuidv4 library. 

- [x] The examples should be changed to eg. '11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000'. 
- [x] The link UUID pattern should be removed from specification (if needed, the application can do the validation explicitly using `import { isUuid } from 'uuidv4';`

**Comment by IswaryaaS** [comment]
Created issue based on decision made on https://github.com/openBackhaul/ApplicationLayerTopology/issues/262

**Comment by openBackhaul** [comment]
Changed as proposed.
