### ISSUE TITLE
Update descriptions for control construct path

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationLayerTopology#287]
The descriptions in ALT specification needs to be updated to omit network-control-domain. The concept of network-control-domain is no longer needed, as all control constructs will be stored under one index (each control construct will be a document) and all links will be stored under other index (each link will be a document).

Please remove from specification description:

- [x] Instead of:

 `description: > 'Documentation of an interface at an application update or create [ElasticSearch://core-model-1-4:network-control-domain/control-construct=*/logical-termination-point=*/]'`

Put:  `description: > 'Documentation of an interface at an application update or create [ElasticSearch://logical-termination-point=*/]'`

- [x]  Instead of:

`description: >  'UUID of Link  from [ElasticSearch://core-model-1-4:network-control-domain/link=*/uuid]'`

Put: `description: >  'UUID of Link from [ElasticSearch://link=*/uuid]'`

Reference #246

**Comment by PrathibaJee** [comment]
•	In ALT , the control-construct of each regarded application is stored as a document under a single index in the ElasticSearch.
•	Each such document comprises of the content of the control-construct(i.e. logical-termination-point, forwarding-domain, uuid)

So , wherever we are referring the l**ogical-termination-point**, **forwarding-construct** , it should have the prefix **ElasticSearch://logical-termination-point=*/** , **[ElasticSearch://forwarding-domain=*-op-fd-000/forwarding-construct=** respectively.

Also , please find the below snapshot( from the ElasticSearch in the laboratory). 
![image](https://github.com/openBackhaul/ApplicationLayerTopology/assets/62344562/91dca0d2-bfc0-4618-b06d-3de02e575031)

**Comment by openBackhaul** [comment]
Changed as proposed.
