### ISSUE TITLE
Typo: uuid to be updated to new uuid format in example

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#301]
In OAS, /v1/list-end-points-of-link, responses :: 200 :: example :: the uuid has been present in old uuid format which needs to be updated to new uuid format. 

Here, in line 3069, the operation-uuid of RO should be **ro-2-0-1-op-c-im-alt-1-0-0-000** corresponds to operation-server alt-2-0-1-op-s-bm-001

**Comment by openBackhaul** [comment]
Changed as proposed.
