### ISSUE TITLE
ALT responds 200 even without configured to ES

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#318]
It is expected that GET /core-model-1-4:control-construct responds 500 Internal server error when configuration to ElasticSearch (ES) fails. Currently, in server/controllers/Core.js getControlConstruct(), response to be updated as below 

```
response['application/json'] = {
        "core-model-1-4:control-construct": await elasticsearchService.updateControlConstructWithServicePolicy(value)
      };
```
instead of 
```
response['application/json'] = {
        "core-model-1-4:control-construct": value
      };
```

**Comment by vanithavalluripalli9** [comment]
As , ApplicationLayerTopology is not having any service record policy we are not updating the controlconstruct with service record policy .
