### ISSUE TITLE
Deleting of FC port is not ported to Elasticsearch

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationLayerTopology#319]
Probably due to miscommunication, part of the code that was supposed to be deleting fc-port from Elasticsearch, is still trying to remove fc-port from load file. This causes every _delete-ltp-and-dependants_ request from any testsuite to fail.

**Comment by vanithavalluripalli9** [comment]
delete-fc-port service is working as expected . can we edit the issue only for delete-ltp-and-dependents

**Comment by DanaSunal** [comment]
Closed, already implemented in the PR.
