### ISSUE TITLE
/v1/register-yourself service RequestHeaders require changes when RequestBody is empty

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#390]
In the basic service , in the register-yourself service , when the incoming request comes with no requestBody , the following adjustments shall be made in the controller,
```
 if (Object.keys(req.body).length === 0) {
      body = req.body;
      user = req.headers["user"];
      originator = req.headers["originator"];
      xCorrelator = req.headers["x-correlator"];
      traceIndicator = req.headers["trace-indicator"];
      customerJourney = req.headers["customer-journey"]; 
    }
```
>Priority:High;
>AffectedFlow:Registration/register-yourself;

**Comment by DanaSunal** [comment]
IMHO, this whole headers not matching should be fixed either in the specification or in OAS3tools, it should never enter the server side code.
