### ISSUE TITLE
/v1/regard-application shall not wait for callback

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#424]
IN ALT, /v1/regard-application is awaiting for callbacks (/v1/redirect-topology-change-information) and link creation in ES. 

This behavior is not expected. As per AP architecture, once the basic configuration is done response shall be sent to user and the rest of callback process shall be done in background. 
Further analysis shall be made in EATL based on x-correlator

**Comment by DanaSunal** [comment]
The callback was added because of this issue:

https://github.com/openBackhaul/ApplicationLayerTopology/issues/348
