### ISSUE TITLE
Testexecution PostTermination mismatch in the initial and final configuration file - individual services

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#435]
**Assertion failure details**
In ALT Individual Services , following are the assertions that are failed because of this problem, 

 1. Provides expected properties in configuration class for 'alt-2-0-1-tcp-s-000'
 2. Provides expected length of client-ltp list for 'alt-2-0-1-http-c-es-1-0-0-000'
 3. LTP instance 'alt-2-0-1-op-c-im-cc-1-0-0-004' could be found
 4. LTP instance 'alt-2-0-1-http-c-cc-1-0-0-000' could be found
 5. LTP instance 'alt-2-0-1-tcp-c-cc-1-0-0-000' could be found
 6. Provides expected number of fc-port instances '11' in forwarding-construct
 7. Fc-port of local-id '207' could be found in actual 
 8. Provides expected properties in configuration class for 'alt-2-0-1-op-s-bs-000'
 9. Provides expected properties in configuration class for 'alt-2-0-1-op-s-bs-001'
10. Provides expected properties in configuration class for 'alt-2-0-1-op-s-bs-002'
11. Provides expected properties in configuration class for 'alt-2-0-1-op-s-bs-003'
12. Provides expected properties in configuration class for 'alt-2-0-1-op-s-bs-004'
13. Provides expected properties in configuration class for 'alt-2-0-1-op-s-bs-005'
14. Provides expected properties in configuration class for 'alt-2-0-1-tcp-c-or-1-0-0-000'
15. Provides expected properties in configuration class for 'alt-2-0-1-op-c-bm-ro-2-0-1-000'

**Reason  :**
In the test execution, the expectation is , the initial configuration file should match the final configuration.
But there is a mismatch. This mismatch are consequences of the failures of other assertions. Once the other assertion failures will be resolved , this shall also be cleared.

>Priority:Low;
>AffectedFlow:None;

**Comment by IswaryaaS** [comment]
Closing the issue as it is outdated
