### ISSUE TITLE
link-port without logical-termination-points are getting created for regarded application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#437]
when a link is available in ALT and if the application is regarded once again , we could able to see link-ports with no logical-termination-points gets added. This makes the /v1/list-end-points-of-link to fail with 500 internal error.

![image](https://github.com/openBackhaul/ApplicationLayerTopology/assets/62344562/576d92f2-04c1-4407-ae23-5f2c59b3a965)

**Comment by DanaSunal** [comment]
Should be already fixed by #430 .

**Comment by DanaSunal** [comment]
Fixed by #430.
