### ISSUE TITLE
Request to remove LinkUpdateNotificationCausesRequestForLinkEndPoints

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/ApplicationLayerTopology#444]
While implementing callbacks for preapproved links I noticed a considerable amount of requests pinging back to forth between ALT and OKM.
When a new link is added to ALT:
1. ALT ---> OKM : regard-update-link  (request body is linkUuid)
2. OKM ---> ALT : list-end-points-of-link (request body is linkUuid, response body are link endpoints)
3. OKM ---> ALT : update-operation-key

When OKM does scheduleKeyRotation, the process is similar:
1. OKM ---> ALT : list-link-uuids (response body are linkUuids)
2. for each linkUuid: OKM ---> ALT : list-end-points-of-link
3. for each linkUuid: OKM  ---> ALT : update-operation-key

This request is about removing additional step from OKM to ALT by allowing ALT to send link endpoints in request body of regard-update-link (same for list-link-uuids).
Further optimization can be achieved by allowing regard-update-link to consume an array of such links.

Note, that each call for list-end-points-of-link  has to retrieve this information from Elasticsearch in multiple steps, first the link is retrieved based on linkUuid, second, the control construct for EACH link input is retrieved too. (Meaning a link with one input and 7 outputs has to go to ES 9 times).
Note as well, that each forwarding also triggers a forwarding to EATL and a query to ES to record-service-request.

Allowing a link to be sent to OKM instead of just uuid will significantly reduce unnecessary traffic between applications and to Elasticsearch.

### **Some numbers (current state):**
There are 95 preapproved links. These links are saved to Elasticsearch and after that, the forwardings are triggered.

Total number of forwardings sent for each link: 6  (1x regard-update-link, 1x list-endpoints-of-link, 1x update-operation-key + 3x record-service-request)
Total number of forwardings = **570**
Number of ES queries sent for each link: 6 at least (1x add-link,  2x list-endpoints-of-link, 3x record-service-request)
Total number of ES queries = **570+**

### **Removing forwarding to list-end-poins-of-link:**
Total number of forwardings sent for each link: 4  (1x regard-update-link, 1x update-operation-key + 2x record-service-request)
Total number of forwardings = **380**
Number of ES queries sent for each link: 3 (1x add-link,  2x record-service-request)
Total number of ES queries = **285**

### **Sending an array of links:**
Total number of forwardings = **192** (1x regard-update-link + 95x update-operation-key + 96x record-service-request)  
Total number of ES queries = **95**  (95x add new link + 96x record-service-request)

**Comment by openBackhaul** [comment]
ALT is now sending link endpoints in request body of OKM://regard-update-link, too.  

It seems that one or two other changes have been considered but not clearly worked out.  
ALT://list-link-uuids not only responding the LinkUuids, but also the Link-end-points might be considered.  
But this seems to be a quite extensive dataset, which is then processed over several minutes.

Perhaps, it would be more effective to consider not to sent EaTL://record-service-request when ALL://update-operation-key has been activated.
