### ISSUE TITLE
alt-2-0-1-op-s-is-022 to be added to INPUT fc-port of ServiceRequestCausesLtpUpdateRequest and ServiceRequestCausesFcUpdateRequest

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#449]
**alt-2-0-1-op-s-is-022** is operation-server uuid of /v1/notify-link-updates. 

This service shall be added to INPUT fc-port of _ServiceRequestCausesLtpUpdateRequest_ and _ServiceRequestCausesFcUpdateRequest_ as this will be creating and updating ltp and fc-port instances and the update in LTP shall be sent to _/v1/update-ltp and /v1/update-fc_ for storing them in control-construct of ALT in _ElasticSearch_

This needs to be updated in [forwardings.yaml](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bforwardings.yaml) and [config.json ](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bconfig.json) files

**Comment by openBackhaul** [comment]
Changed as proposed.
