### ISSUE TITLE
To initiate the forwardings(in bequeath-your-data-and-die) that transfers the application data(even if the old-release is "OldRelease")

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#463]
As of now, we have the concept , 
1. “/v1/ embed-yourself” will initiate the forwarding “/v1/ bequeath-your-data-and-die”
2. “/v1/ bequeath-your-data-and-die” will be performed if the old release LTP instance’s "application-name!= OldRelease " 

As a part of bequeath-your-data-and-die , the following will happen , 
1. Transferring of application data
2. Redirecting notifications from OldRelease to NewRelease
3. Ending the subscription of OldRelease
4. Relaying the server replacement
5. Deregistering the OldRelease from the ApplicationLayer

This concept ensures that "end-subscription" and "application-deregistration" callbacks in the "bequeath-your-data-and-die" will not be executed if the application actually don’t have a preceeding version.

“Transferring of application data" in all the TAC applications(except ALT) results in transferring the tcp/http/operation-client 
But in ALT , “Transferring of application data” will not only transfer the tcp/http/operation-client between applications , 
but also the result(response-body) from the further forwarding needs to be updated in the application-data
“/v1/ bequeath-your-data-and-die” --> “/v1/regard-application” --> “/v1/redirect-topology-change-information” ( which provides the control-construct of the application )

"transferring of application data" , for ApplicationLayerTopology(ALT) , when a new application gets regarded , along with the tcp/http/operation client information updation , the response(ControlConstruct) from the callback of “redirect-topology-change-information” will also be update the application data(Elastic search)

For this reason , ALT needs to perform the “data transfer step” in the bequeath-your-data-and-die service to trigger the callback.

<details>
<summary>
Some References : 
</summary>

TACApp --> register-yourself --> RO
TAR --> regard-updated-approval-status --> RO --> regard-application --> TAC apps(incl ALT)
ALT --> redirect-topology-change-information --> TACApp 
TACApp --> Control-construct of NewApp --> ALT
ALT updates the application data(Elastic search)
</details>

**Note :** Issue is specific to TAC.This problem happens for the applications that are deployed before the ALT's deployment. 
**Current workaround** : Initiating the Register-yourself of the TAC applications **once again** solves this problem.

**Highlevel proposals :** 
1. Including the data transfer step as a part of embed-yourself.
2. Since bequeath-your-data-and-die is an individual service, we shall customize this service to perform the "data transfer step" even if the application-name of the oldRelease instance is "OldRelease". (By including a description)

**Comment by openBackhaul** [comment]
The idea is to automatically trigger RO and TAR to send their ControlConstruct to ALT as a part of the embedding, to suspend the manual activity.

**Proposed Solution:**
- Adding forwarding "PromptForEmbeddingCausesRetrievingControlConstructFromRoAndTar" with alt-2-0-1-op-fc-im-109 as an InvariantProcessSnippet without management requests, but /v1/embed-yourself as initiating-request and RO://redirect-topology-change-information plus TAR://redirect-topology-change-information as consequent-requests.
- alt-2-0-1-op-fc-im-109 shall be added between alt-2-0-1-op-fc-bm-001 and alt-2-0-1-op-fc-bm-002 in the ForwardingList.
- A diagram to be created for the new forwarding.
- The HttpClient and TcpClient of the TAR and the /redirect-topology-change-information as consequent-requests OperationClient of both RO and TAR have to be documented in the ServiceList.
- This forwarding has also to be documented in the CONFIGfile
- A corresponding Callback with one Request definition that references two addresses (RO and TAR) in the OAS.

**Comment by openBackhaul** [comment]
Changed as proposed.
