### ISSUE TITLE
To Autocreate framework related links for approved applications.

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#479]
Once an application is approved by a TypeApprover , RegistryOffice will regard that application to all the TinyApplicationController.
This means that , the application is approved and can be embedded into the ApplicationLayer.
As of now , an admin have to approve the following forwardings to enable the secured communication ,
1. ServiceRequestCausesLoggingRequest (to ExecutionAndTraceLog://v1/record-service-request)
2. OamRequestCausesLoggingRequest (OamLog://v1/record-oam-request)
3. OamRequestCausesInquiryForAuthentication (AdministratorAdministration://v1/approve-oam-request)
4. ServiceRequestCausesLtpUpdateRequest (ApplicationLayerTopology://v1/update-ltp)
5. ServiceRequestCausesLtpDeletionRequest (ApplicationLayerTopology://v1/delete-ltp-and-dependents)
6. ServiceRequestCausesFcUpdateRequest (ApplicationLayerTopology://v1/update-fc)
7. ServiceRequestCausesFcPortUpdateRequest (ApplicationLayerTopology://v1/update-fc-port)
8. ServiceRequestCausesFcPortDeletionRequest (ApplicationLayerTopology://v1/delete-fc-port)

**Comment by openBackhaul** [comment]
Discussion on 10th of October 2023:
Good idea to automate the creation/approval of the Basic management connections (it's like a type approval of the Basic management connections). 
It should not be a problem specifying ALT 2.1.0 instead of ALT 2.0.2.

**Comment by openBackhaul** [comment]
The operation for allowing some new application to address the management paths at the TinyApplicationControlelr is
ALT://v1/add-operation-client-to-link. 
It requires:
- serving-application-name
- serving-application-release-number
- operation-name
- consuming-application-name
- consuming-application-release-number

It is proposed that EaTL, OL, AA and ALT are addressing the ALT://v1/add-operation-client-to-link after receiving /v1/regard-application from RO, but before subscribing at the new application for the respective service.  
(ALT would need to execute multiple self-calls.)

**Comment by PrathibaJee** [comment]
Kindly please consider the following points , 
1. To add an operation-client to a link , consuming application's control-construct needs to be available in the ApplicationLayerTopology's(ALT) database
2. So , if AdministratorAdministrator(AA) receives /v1/regard-application from RegistryOffice  before ALT (or) if ALT is yet to finish updating the control-construct of the newApp in its database, then , the  ALT://v1/add-operation-client-to-link request sent by AA cannot be processed.
3. We need to ensure that ALT's database should be updated before receiving the ALT://v1/add-operation-client-to-link from AA.

**Comment by openBackhaul** [comment]
Changed as proposed.
