### ISSUE TITLE
OAS : basic services : properties description : reference URI format change

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#5]
In the yaml specification -> basic services -> description of each property -> the reference path URI structure is being left in the format followed earlier in other tiny applications, here which would be following the format like **[/core-model-1-4:network-control-domain/control-construct=*/]..**

for example, In the service request /v1/register-yourself , under description of the property registry-office-application, it is **“find or create [/core-model-1-4:control-construct/logical-termination-point=*-0-0-1-http-c-0020/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-capability/application-name]”**, which would be actually **“/core-model-1-4:network-control-domain/control-construct=alt-0-0-1/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-capability/application-name”**. 

_Similar occurrences of older reference URI could be found in other properties of the same request as well as in the other requests under Basic services of ALT._

**Comment by openBackhaul** [comment]
In the services section, the descriptions at the attributes shall indicate the locations of  the values in the internal (and CONFIGfile) data structure.
The data structure at the ALT is a little deeper than usual.
All location descriptions, which are referencing the configuration of the ALT itself, have to start with " [/core-model-1-4:network-control-domain/control-construct=alt-0-0-1/...] ".

This is correctly done for the Individual Services of the ALT.
**But the Basic Services have just been copied into the OAS of the ALT without updating the descriptions at the attributes**.
The descriptions at the Basic Services should be updated.

**Comment by openBackhaul** [comment]
[Decision in the comment above](https://github.com/openBackhaul/ApplicationLayerTopology/issues/5#issuecomment-1152252785) got reversed.
ALT issue #132 describes off-loading topology information into an external database and to store ALT specific configuration information in a "standard" CONFIGfile format.
Consequently, all descriptions have to be changed back into the standard format starting with "_[/core-model-1-4:control-construct/logical-termin..._".

Necessary changes will be documented and tracked in ALT issue #132.
This issue got obsolete.
