### ISSUE TITLE
Problem in updating the operation-key until a new application is regarded to OperationKeyManagement application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#505]
As per the new embedding procedure , a new application will be embedded in the following order to the TinyApplicationControllers, 
1. ALT
2. OKM
3. EATL
4. AA
5. OL

As a part of the /v1/regard-application procedure in ALT , 
ALT will ,
1. create link between the "/v1/redirect-topology-change-information" of the client application(ALT) and the serving application(NewApplication), 
2. notify the created link to OKM 

Further , OKM will try to set the operation-key in both the involved end-points.
OKM will ,
1. set the operation-key to ALT
2. fail to set the operation-key in the serving application(NewApp). 
**Reason :** The new application is not yet regarded to OKM and OKM will not know the TCP/IP information about the new Application.

![image](https://github.com/openBackhaul/ApplicationLayerTopology/assets/62344562/42a5334d-00af-4ceb-a1f5-c13031422e0a)

**Possible proposals :**
**Proposal#1 :** 
After getting the ControlConstruct from the new Application , ALT shall regard the new application to OKM.(by Thorsten)

**Proposal#2 :**
ALT will send the details of the link-id to OKM using the /v2/regard-updated-link API.
A sample of the requestBody is as below , 
```diff
{
  "link-uuid": "11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000",
  "link-end-point-list": [
    {
      "application-name": "RegistryOffice",
      "release-number": "2.0.1",
      "operation-uuid": "ro-2-1-0-op-c-im-alt-1-0-0-000",
+     "ltp-direction": "core-model-1-4:TERMINATION_DIRECTION_SINK"
    },
    {
      "application-name": "ApplicationLayerTopology",
      "release-number": "2.0.1",
      "operation-uuid": "alt-2-0-1-op-s-bm-001",
+     "ltp-direction": "core-model-1-4:TERMINATION_DIRECTION_SOURCE"
    }
  ]
}
```

On receiving a /v2/regard-updated-link , 
OKM shall look for the **"ltp-direction": "core-model-1-4:TERMINATION_DIRECTION_SOURCE"**
If the **"application-name" + "release-number" client stack is not available in its configuration** 
then 
OKM shall **set the default operation key "Operation key not yet provided" to the consuming application**.

So , an "update-operation-key" call will be triggered to the consuming application( In our case ALT will receive trigger to respond back to RegistryOffice )

**Comment by openBackhaul** [comment]
Proposal #2 seems to be really good idea.

**Comment by openBackhaul** [comment]
Changed as proposed.
