### ISSUE TITLE
spec/diagrams/Readme.md file shall be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#506]
[spec/diagrams/Readme.md](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/diagrams/README.md) needs to be updated to contain the content of ApplicationLayerTopology.

Currently it contains the content of MicrowaveDeviceGateKeeper Diagrams which shall be updated.

**Comment by openBackhaul** [comment]
readme updated with references on the relevant diagrams.
