### ISSUE TITLE
serviceView/is001_regardApplication diagram may be updated for response

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#508]
As per recent change in version 2.1.0, the service /v1/regard-application has been updated to send a response-body as response after internal processing. 

In the diagram [serviceView/is001_regardApplication](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/diagrams/ServiceView/is001_regardApplication.png), which represents the actual workflow of this service, can we also include a line from ALT to RO _(i.e. after note NewApplicationCausesRequestForTopologyChangeInformation)_  representing the response-body . 

This would give a understanding that a response-body shall be sent after all the internal processing in ALT .  Kindly let me know your views.

**Comment by openBackhaul** [comment]
Changed as proposed.
