### ISSUE TITLE
typo: attribute name in description of  /v1/list-links-to-operation-clients-of-application shall be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#510]
In the description of service /v1/list-links-to-operation-clients-of-application (line 3971), the attribute name is mentioned as application-release-number. 

since the request-body attribute name has been changed to release-number, can we also update the name to release-number instead of application-release-number.

**Comment by openBackhaul** [comment]
Changed as proposed.
