### ISSUE TITLE
service.yaml file : remove uuid(s) from client of NewRelease instance

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#511]
In[ service.yaml](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bservices.yaml) file, the uuids alt-2-1-0-op-c-im-nr-2-1-0-001 and alt-2-1-0-op-c-im-nr-2-1-0-002 could be removed from operation-client list of NewRelease instance. Because, they are no longer used for transferring data from OldRelease to NewRelease.

**Comment by openBackhaul** [comment]
Corrected as proposed.
