### ISSUE TITLE
forwardings.yaml : LinkChangeNotification: /v1/end-subscription shall be removed from operation-client-deletion

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#514]
Since, /v1/end-subscription is only responsible for deleting an fc-port and not operation-client ltp instance, we could delete /v1/end-subscription from LinkChangeNotification forwarding-constuct in [forwardings.yaml](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bforwardings.yaml) file. 
(Note: need not remove it from config file)

Reference:
Decision that /v1/end-subscription shall only remove fc-port instance and not operation-client instance has been made in https://github.com/openBackhaul/ApplicationPattern/issues/285

**Comment by openBackhaul** [comment]
Corrected as described.
