### ISSUE TITLE
Callback RequestForInquiringTopologyChangeInformationWithDefaultKey shall not have alt-2-1-0-op-s-bm-010 in INPUT fc-port

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#516]
In [config.json](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bconfig.json) file, under forwarding-construct **NewApplicationCausesRequestForTopologyChangeInformation.RequestForInquiringTopologyChangeInformationWithDefaultKey**,  since this callback is not triggered based on /v1/update-operation-key (alt-2-1-0-op-s-bm-010), the INPUT fc-port with logical-termination-point with alt-2-1-0-op-s-bm-010 shall be removed.

**Comment by openBackhaul** [comment]
Changed as proposed.
