### ISSUE TITLE
Callback RequestForInquiringTopologyChangeInformation shall not contain alt-2-1-0-op-s-is-001 in initiating-requests list

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#517]
In [forwardings.yaml ](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bforwardings.yaml) file, under forwarding-construct NewApplicationCausesRequestForTopologyChangeInformation.RequestForInquiringTopologyChangeInformation, as the callback is triggered after receiving /v1/update-operation-key and not /v1/regard-application,  the instance in initiating-request with uuid alt-2-1-0-op-s-is-001 (/v1/regard-application) could be removed. 

(Note: in config file, only INPUT fc-port for /v1/update-operation-key is available )

**Comment by openBackhaul** [comment]
I think both must be received for triggering the consequent-request of this forwarding.
Changed the CONFIGfile instead and added alt-2-1-0-op-s-is-001 as an initiating-requests.
