### ISSUE TITLE
/v1/update-client-of-subsequent-release shall be included in INPUT fc-port of ServiceRequestCausesLtpUpdateRequest

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#518]
Since, /v1/update-client-of-subsequent-release could update ltp instances in load file, this shall be eligible for sending a LTPUpdate request to ALT. 
In forwarding-construct ServiceRequestCausesLtpUpdateRequest, /v1/update-client-of-subsequent-release (alt-2-1-0-op-s-bm-015) is to be added into INPUT fc-port list. 

The change is required in both [config.json](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bconfig.json) and [forwardings.yaml](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bforwardings.yaml) files.

**Comment by openBackhaul** [comment]
Changed as proposed.
