### ISSUE TITLE
To remove unused APIs in the bequeath-your-data-and-die callbacks

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#519]
In the new specification , the following APIs are marked as deprecated and will not be available from 3.0.0,

/v1/notify-deregistrations
/v1/notify-approvals
/v1/notify-withdrawn-approvals

Based on above understanding, the following callbacks shall be removed from bequeath-your-data-and-die callbacks.
- PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease (for /v1/notify-approvals)
- PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease (for /v1/notify-withdrawn-approvals)
- PromptForBequeathingDataCausesRObeingRequestedToStopNotificationsToOldRelease (for /v1/end-subscription). 

These forwardings shall be removed from 
 - OAS 
 - forwardings.yaml 
 - config.json 
 - service.yaml

Similar issue : https://github.com/openBackhaul/RegistryOffice/issues/528

**Comment by openBackhaul** [comment]
Changed as proposed.
