### ISSUE TITLE
A second es-c shall be added to ElasticSearch instance of config file

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#521]
As per decision made in [issue#246](https://github.com/openBackhaul/ApplicationLayerTopology/issues/246), ALT is expected to have two indexes in Elastic search (one for link and the other for storing control-construct instances). 
Hence, the config file shall have two es-c instances for ElasticSearch client as below.
- alt-2-1-0-es-c-es-1-0-0-000 for storing control-construct instances of client applications with index-alias = alt-2-0-1
- alt-2-1-0-es-c-es-1-0-0-001 for storing link information with index-alias = alt-links-2-0-1

This shall be added to [config.json ](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bconfig.json) and [services.yaml ](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/spec/ApplicationLayerTopology%2Bservices.yaml) file of ALT.

**Comment by openBackhaul** [comment]
Changed as proposed.
