### ISSUE TITLE
The diagram  ServiceView/is002_disregardApplication shall be updated. 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#537]
The diagram for /v1/disregard-application under the path https://github.com/openBackhaul/ApplicationLayerTopology/blob/v2.1.1_spec/spec/diagrams/ServiceView/is002_disregardApplication.plantuml shall be updated . 

In the above diagram, since the service /v1/disregard-application does not result in callback NewApplicationCausesRequestForTopologyChangeInformation, this statement shall be removed from line 22. 

On a side note: Also, the updated plantuml shall be copied to the png file as well.

**Comment by openBackhaul** [comment]
Covered by pull-request [#566](https://github.com/openBackhaul/ApplicationLayerTopology/pull/566)
