### ISSUE TITLE
/v1/update-ltp service implementation shall be updated 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#538]
The existing implementation of /v1/update-ltp shall be updated for the following scenarios

- [x] shall not update/create op-s, http-s, tcp-s ltp instances
- [x] is not creating new ltp instances for op-c, http-c or tcp-c instances

**Comment by IswaryaaS** [comment]
reverting the change " shall not update/create op-s, http-s, tcp-s ltp instances" because the scenario " there is a change when a tcp-server/ip-address or port could be updated" .

**Comment by PrathibaJee** [comment]
@IswaryaaS , Many thanks for fixing this issue. Issue merged in the PR https://github.com/openBackhaul/ApplicationLayerTopology/pull/547 , hence closing this.
