### ISSUE TITLE
Update trace-indicator in regard-application

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#545]
Update trace-indicator value in regard-application in following scenarios

- After sending forwardings to ALT before the regardApplication embedding process starts
- After sending regardUpdatedLink to OKM during linkCreation under RequestForInquiringTopologyChangeInformationWithDefaultKey
- After sending regardUpdatedLink to OKM during linkCreation under RequestForInquiringTopologyChangeInformation

**Comment by PrathibaJee** [comment]
@IswaryaaS , Many thanks for fixing this issue. Issue merged in the PR https://github.com/openBackhaul/ApplicationLayerTopology/pull/547 , hence closing this.
