### ISSUE TITLE
OAS : callback uri definition : /v1/regard-application

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#55]
Problem:

Operation-name is statically defined in callback request "NewApplicationCausesRequestForLatestTopologyInformation" and "NewApplicationCausesRequestForTopologyChangeInformation"

Proposal:

- Line 1488 to be changed from "https://{$request.body#application-address}:{$request.body#application-port}/v1/list-ltps-and-fcs" to "https://{$request.body#application-address}:{$request.body#application-port}[/core-model-1-4:control-construct/logical-termination-point=alt-0-0-1-op-s-0008/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]"
- Line 1882 to be changed from "https://{$request.body#application-address}:{$request.body#application-port}/v1/redirect-topology-change-information" to "https://{$request.body#application-address}:{$request.body#application-port}[/core-model-1-4:control-construct/logical-termination-point=alt-0-0-1-op-s-0009/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]"

Related issue : https://github.com/openBackhaul/OamLog/issues/6

**Comment by openBackhaul** [comment]
@openBackhaul: Double check references into RequestBody.
