### ISSUE TITLE
OAS : /v1/notify-link-updates : request-body schema description to be made specific for OKM 

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#59]
The service /v1/notify-link-updates is a service that enables OperationKeyManagement application to subscribe for any update in links.

Error description:
In description of the request-body attributes, the reference path points to random application (like alt-0-0-1-http-c-*) 

Proposal:
The reference paths of all attributes could be made specific to OKM.

For example, 
for subscriber-application , currently the path is /core-model-1-4:network-control-domain/control-construct=alt-0-0-1/logical-termination-point=**alt-0-0-1-http-c-***/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-capability/application-name which could be changed to _/core-model-1-4:network-control-domain/control-construct=alt-0-0-1/logical-termination-point=**alt-0-0-1-http-c-2080**/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-capability/application-name_

Similarly paths could be changed for attributes
- subscriber-release-number (alt-0-0-1-http-c-2080)
- subscriber-operation (alt-0-0-1-op-c-3080)
- subscriber-address (alt-0-0-1-tcp-c-2080)
- subscriber-port (alt-0-0-1-tcp-c-2080)

**Comment by openBackhaul** [comment]
UPDATA 5th of December 2022:
ALT shall be open for future applications to subscribe for notifications about Link updates.
Consequently, storing of address information, which is sent in the RequestBody, shall not be limited to the *Clients of the OKM.
This design corresponds to the current specification and implementation.
@IswaryaaS : If you would agree and also see no need for change, please close the issue.

**Comment by IswaryaaS** [comment]
Thanks for making me understand the expectation. Hence closing the issue
