### ISSUE TITLE
OAS : clarification for service /v1/redirect-topology-change-information

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#6]
We have the service **/v1/redirect-topology-change-information**, which the ApplicationLayerTopology application subscribes another application in the MS environment for getting notified for changes in the LTP or FC of the application. In this case , the application being subscribed is the same application (ALT) which forces the changes happening in LTP and FC to change again in the ALT itself. This seems to be a process that finally has no effect on the data-file structure. 

I could see that since it is a basic service, we are having it in ALT as well, but my concern is, since ALT has been subscribed to all other applications in ALT which will result in very frequent changes in it's own LTP and FC due to changes in other application's load file, which in turn will result in many follow up callbacks (as we have 11 callbacks for the request) due to change in its own LTP and FC, which night not have any extra effect in the load-file. Please let me know if there is any specific reason on having the service request.

Note : Similar to [issue 4](https://github.com/openBackhaul/ApplicationLayerTopology/issues/4)

**Comment by openBackhaul** [comment]
Obsolete due to decision in issue #4.
