### ISSUE TITLE
Load file : detailed-logging-is-on attribute to be removed from logical-termination-point instances

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#63]
As per understanding, detailed-logging-is-on attribute is applicable only for the operation "/v1/record-service-request" of ExecutionAndTraceLog

Problem Description:
In load-file, [ApplicationLayerTopology_0.0.2_tsi.220110.1955+data.2.json](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/ApplicationLayerTopology_0.0.2_tsi.220110.1955%2Bdata.2.json),  for ltp instance alt-0-0-1-op-c-2040 and alt-0-0-1-op-c-2041 contains an additional attribute _detailed-logging-is-on_, which needs to be removed.
Also an update needed in database/load-file of server 

Note : 
- alt-0-0-1-op-c-2040 refers to  /v1/redirect-topology-change-information
- alt-0-0-1-op-c-2041 refers to /v1/list-ltps-and-fcs

Related issues:
https://github.com/openBackhaul/AdministratorAdministration/issues/40
https://github.com/openBackhaul/OperationKeyManagement/issues/32
https://github.com/openBackhaul/OamLog/issues/41
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/47

**Comment by openBackhaul** [comment]
Friday call on 12.08.: Attribute shall just be removed from LOADfiles where it is not required.

**Comment by openBackhaul** [comment]
Done.
/v1/record-service-request is only OperationClient with detailed-logging-is-on attribute.
