### ISSUE TITLE
Load-file : client-ltp and server-ltp of alt-0-0-1-http-c-2300 needs to be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#65]
problem description:
In load-file [ApplicationLayerTopology_0.0.2_tsi.220110.1955+data.2.json](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/ApplicationLayerTopology_0.0.2_tsi.220110.1955%2Bdata.2.json), 
1. the uuid "alt-0-0-1-op-c-2301" is missing from the client-ltp list of _alt-0-0-1-http-c-2300_ , which needs to be added
2. the uuid "alt-0-0-1-tcp-c-2301" in server-ltp list of _alt-0-0-1-http-c-2300_ needs to be removed. (also in server/database/load-file.json)

Note:
- alt-0-0-1-http-c-2300 refers to CurrentController
- alt-0-0-1-op-c-2301 refers to /v1/list-ltps-and-fcs

**Comment by openBackhaul** [comment]
Done.
