### ISSUE TITLE
/v1/list-applications : implementation to be changed

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#67]
Summary:
As per OAS, the individual service /v1/list-applications should retrieve http-s (application-name and application-release-number) from LTP of all application instances present in the control-construct list. But, the server is retrieving values from http-c of alt-0-0-1.

Example:
The response-body values should be retrieved from _/core-model-1-4:network-control-domain/control-construct=*/logical-termination-point=*-0-0-1-http-s-0000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/application-name_ and _/core-model-1-4:network-control-domain/control-construct=*/logical-termination-point=*-0-0-1-http-s-0000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-number_

Instead, the actual values are referred from _/core-model-1-4:network-control-domain/control-construct=alt-0-0-1/logical-termination-point=alt-0-0-1-http-c-*/layer-protocol=0/http-clienr-interface-1-0:]http-client-interface-pac/http-client-interface-capability/application-name_ and _/core-model-1-4:network-control-domain/control-construct=alt-0-0-1/logical-termination-point=alt-0-0-1-http-c-*/layer-protocol=0/http-clienr-interface-1-0:]http-client-interface-pac/http-client-interface-configuration/release-number_

**Comment by PrathibaJee** [comment]
Changed the implementation as per the specification. Now , the the individual service /v1/list-applications will retrieve http-s(application-name and application-release-number) from LTP of all application instances present in the control-construct list.
