### ISSUE TITLE
OAS : Clarification required in the summary of the service /v1/delete-ltp-and-dependents

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#7]
The summary of the service /v1/delete-ltp-and-dependents is as below, 
> An **OperationClient** identified by LtpUuid and all its entries in FCs and Links gets deleted

But as per the requestBody/uuid description , by using this service , we can delete any ltp,
> LtpUuid identifying the LTP, which is to be deleted find in [/core-model-1-4:network-control-domain/control-construct=\*-0-0-1/logical-termination-point=**\*-0-0-1-\*-\*-\***/uuid]

Kindly let me know whether we have to change the summary text.

**Comment by openBackhaul** [comment]
It is unclear, whether the service /v1/delete-ltp-and-dependents is restricted on OperationsClient (summary of the service) or shall apply on all kinds of Clients (e.g. HTTP, TCP) as implied in the open description of the UUID. 

If HTTP or TCP Clients shall also be covered, proceeding with client layers has to be documented, too.
E.g. If HttpClient gets deleted, associated OperationsClients shall be deleted, too.
