### ISSUE TITLE
FC : LinkChangeNotification : to be updated as INVARIANT_PROCESS_SNIPPET

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/ApplicationLayerTopology#79]
The OperationKeyManagement(OKM) application subscribes to get notified for any update in links through the service /v1/notify-link-updates. 

Problem statement:
The Forwarding-construct "LinkChangeNotification" is currently of ForwardingKind _FORWARDING_KIND_TYPE_SUBSCRIPTION_ which implies that more than one application/operation can subscribe to /v1/notify-link-updates (more than one output-port is created and updates are forwarded to all the output-ports)

Proposal:
Since, OKM is only applicable for subscription, can we update the forwarding-construct "LinkChangeNotification" to be an _INVARIANT_PROCESS_SNIPPET_

Related issue: https://github.com/openBackhaul/ApplicationLayerTopology/issues/59

**Comment by openBackhaul** [comment]
ALT shall be open for future applications to subscribe for notifications about Link updates (see also [comment in ALT issue#59](https://github.com/openBackhaul/ApplicationLayerTopology/issues/59)).
Consequently, the ForwardingConstruct _LinkChangeNotification_ shall stay being of type subscription.
This design corresponds to the current specification and implementation.

@IswaryaaS : If you would agree and also see no need for change, please close the issue.

**Comment by IswaryaaS** [comment]
I agree with the clarification provided as per https://github.com/openBackhaul/ApplicationLayerTopology/issues/59, hence closing the issue.
