### ISSUE TITLE
Circular dependency in approving links to update operation-key

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/ApplicationLayerTopology#83]
When a NewApplication  enters the ApplicationLayer , after RO approves the application , it will send regard-application to all the TinyApplicationControllers(TAC) including ApplicationLayerTopology(ALT). 

consequently , 
- As a callback , ALT will send _Redirect-topology-change-information_ to the NewApplication  to get the LTP and FC details.
- As a callback , NewApplication will send _update-all-ltps-and-fcs_. **This step will work fine only if operation-server of the _update-all-ltps-and-fcs_ in ALT consists of the default operation-key.** (if the OperationKeyManagement(OKM) is operating in reactive/protection mode)

**How NewApplication will get the latest operation-key ?**
In ALT , _add-operation-client-to-link_  service should be used to create a link between the operation-client in NewApplication  and the operation-server in the ALT.
This will initiate a callback(_regard-updated-link_) to the OKM to update operation-key in the client side.
But , without the LTP details of the NewApplication in the ALT's control-construct list , it is not possible to perform the _add-operation-client-to-link_.

So , here we have a circular dependency,
1. NewApplication requires the latest operation-key to perform _update-all-ltps-and-fcs_ in the ALT
2. To update the operation-key , OKM requires the link details from ALT.
3. To update link details to the OKM , ALT requires the LTP details of the NewApplication.

A possible proposal could be providing the latest operation-key of the "update-ltp-and-fcs" service when the NewApplication is approved and regarded to the OKM application.

![image](https://user-images.githubusercontent.com/62344562/192553489-d579740b-51fe-4fba-9fe7-331544eb8022.png)

**Comment by openBackhaul** [comment]
**Potential Solution:**
Instead of a callback with the newApplication addressing update-all-ltps-and-fcs in ALT, the redirect-topology-change-information request, which is sent from the ALT to the new application, shall be answered with the same content of the update-all-ltps-and-fcs request by the new application.
(The response body can be send without having the operation key, which would have been necessary to address update-all-ltps-and-fcs at ALT.)

**Comment by openBackhaul** [comment]
Pull-request openBackhaul/ApplicationPattern#324 has been opened for solving this problem.
Problem will be tracked and solved in openBackhaul/ApplicationPattern#305.
